### ISSUE TITLE
Could this guide also work on Debian/ubuntu based systems?

### ISSUE THREAD

**Issue by revan1611** [BigAnteater/KVM-GPU-Passthrough#12]
Basically the title. I wonder if the scripts could also work on Deb/ubuntu systems besides arch

**Comment by BigAnteater** [comment]
Yes, but it would take some editing and tailoring to fit your system.

**Comment by airborne-commando** [comment]
May be late but try this

https://github.com/Nthompson096/KVM-GPU-Passthrough
