### ISSUE TITLE
ebtables and iptables conflict

### ISSUE THREAD

**Issue by Zorrototo** [BigAnteater/KVM-GPU-Passthrough#3]
When trying to follow the script to setup libvit, I notice an issue for the command `pacman -S libvirt libvirt-glib libvirt-python virt-install virt-manager qemu qemu-arch-extra ovmf vde2 ebtables dnsmasq bridge-utils openbsd-netcat iptables swtpm
` 

`ebtables` is provided by the package `iptables-nft`, and it conflicts with `iptables` so we end up needing to not install `iptables` and/or remove `iptables`

There is an AUR package `ebtables`, should we install it instead? Should we not install `ebtables` at all?

At this point I'm even wondering why there is `ebtables` and `iptables` packages in the install script, are they needed for the whole setup to work?

Thanks for your clarification.

**Comment by BigAnteater** [comment]
These are needed for the setup to make sure that networking works properly. if it asks you to replace the iptables package with iptables-nft, say yes.

**Comment by Zorrototo** [comment]
OK. You shouldn't have the `iptables` package then in your install script, as obviously it would conflict with `iptables-nft` (which provides `ebtables`).

**Comment by BigAnteater** [comment]
> OK. You shouldn't have the `iptables` package then in your install script, as obviously it would conflict with `iptables-nft` (which provides `ebtables`).

iptables is an already installed package along with other networking tools.
