### ISSUE TITLE
Exporting ROM, cat: '/sys/devices/pci0000:00/0000:00:02.0/rom': Input/output error

### ISSUE THREAD

**Issue by pknueppel** [BigAnteater/KVM-GPU-Passthrough#36]
Attempting to test this out on my old laptop, an Acer R3-471T-59UL, running a Intel i5-5200U and a integrated Intel HD Graphics processor, but it does not work.

**Comment by pknueppel** [comment]
Update: The original rom file does list itself as accessed when I attempt this, and a file IS created at the destination with the right name, it's just 0 bytes. Also just found out that as of Linux 5.4, Broadwell CPUs do not support GPU passthrough the same way as others do, so that might be it, but the article that referenced it has an entirely different method...

Update 2: Appears to be an issue with the file itself, can't do anything with it, keep getting an Input/Output error. Unfortunately, I cannot use the original method of exporting the ROM, as a VBIOS for Intel HD graphics from eight years ago is pretty hard to find.

**Comment by sakurawald** [comment]
Get the same error while trying to dump an intel UHD graphics.
