### ISSUE TITLE
Video card ROM improvement suggestion

### ISSUE THREAD

**Issue by Zorrototo** [BigAnteater/KVM-GPU-Passthrough#4]
Instead of downloading the ROM for the video card from a website, and potentially downloading the wrong one, it is easy to extract the actual ROM with a tool like GPUz so the ROM is the proper one. Just an improvement idea on the guide.

**Comment by BigAnteater** [comment]
GPUz is a good method to get the rom, but I had a tricky time running it, and downloading one from a website just seemed easier.
