### ISSUE TITLE
Cant find VIDEO text in my video card rom.

### ISSUE THREAD

**Issue by Thunderzapper** [BigAnteater/KVM-GPU-Passthrough#6]
Searching it in text gives me "The pattern you requested was not found".
Here is the rom if that is helpful.
[Powercolor.RX6600XT.8192.210701.rom](https://www.techpowerup.com/vgabios/236660/Powercolor.RX6600XT.8192.210701.rom)

**Comment by BigAnteater** [comment]
If you happen to have an AMD GPU, you don't need to patch the rom just leave the file as is.
