### ISSUE TITLE
Virtual Machine will not start

### ISSUE THREAD

**Issue by cheeetoo** [BigAnteater/KVM-GPU-Passthrough#8]
Everything seemed to be going well until I was supposed to power it on at the end of the guide. When right-click and run the virtual machine or double click it, nothing happens. How can I fix this?

**Comment by BigAnteater** [comment]
Try re doing the hooks step. Also, make sure your vm is named win10

**Comment by NetuserPRO46** [comment]
Try changing "win10" in /etc/libvirtd/hooks/qemu to your VMs name.
